FROM caddy:latest

RUN cat > /etc/caddy/Caddyfile <<-'EOF'
	{
      debug
	  http_port 8080
	  https_port 8443
	  admin off
	}

	{$CLOUD_HOSTNAME} {
      root * ${$CLOUD_ROOT}

  	  php_fastcgi {$CLOUD_FPM} {
        root ${CLOUD_FCGI_ROOT}
	  }

 	  file_server

	  header {
	    Strict-Transport-Security max-age=31536000;
	  }

	  redir /.well-known/carddav /remote.php/dav 301
	  redir /.well-known/caldav /remote.php/dav 301

	  @forbidden {
	    path /.htaccess
	    path /data/*
	    path /config/*
	    path /db_structure
	    path /.xml
	    path /README
	    path /3rdparty/*
	    path /lib/*
	    path /templates/*
	    path /occ
	    path /console.php
	  }

	  respond @forbidden 404
	}
EOF

